# Generated by Django 2.2.dev20190104142447 on 2019-01-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Actor profile', 'verbose_name_plural': 'Actor profiles'},
        ),
        migrations.AlterModelOptions(
            name='profilegroup',
            options={'verbose_name': 'Actor group', 'verbose_name_plural': 'Actor groups'},
        ),
    ]
