# Generated by Django 2.1.4 on 2018-12-08 14:10

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='Slug'),
        ),
    ]
