# Generated by Django 2.2.1 on 2019-09-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_profilegroup_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                height_field="height",
                null=True,
                upload_to="var/avatars",
                verbose_name="Avatar",
                width_field="width",
            ),
        ),
    ]
