# Generated by Django 2.2.1 on 2019-10-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="var/avatars", verbose_name="Avatar"
            ),
        ),
    ]
