# Generated by Django 2.2.13 on 2020-08-04 12:03

from django.db import migrations, models
import django_extensions.db.fields
import fields.name
import fields.visibility
import fields.weight


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200305_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', fields.name.NameField(help_text='nameHelpText', max_length=63, verbose_name='Name')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visibility', fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2, help_text='visibilityHelpText', verbose_name='Visibility')),
                ('weight', fields.weight.WeightField(default=100, help_text='weightHelpText', verbose_name='Weight')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='name', verbose_name='Slug')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('logo', models.ImageField(upload_to='var/sponsors', verbose_name='Logo')),
                ('on_site', models.BooleanField(default=False, help_text='Display this sponsor on site', verbose_name='On site')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
    ]
