# Generated by Django 2.2.16 on 2020-09-03 20:06

from django.db import migrations
import images.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200824_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=images.fields.ImageField(blank=True, help_text='imageHelpText', null=True, upload_to='var/avatars', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='image',
            field=images.fields.ImageField(height_field='height', help_text='imageHelpText', upload_to='var/photos', verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=images.fields.ImageField(help_text='imageHelpText', upload_to='var/sponsors', verbose_name='Image'),
        ),
    ]
