# Generated by Django 2.2.16 on 2020-09-19 23:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import fields.description
import fields.name
import fields.visibility


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20200903_2206'),
        ('profiles', '0015_auto_20200903_2206'),
        ('events', '0004_update_content_types'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', fields.name.NameField(help_text='nameHelpText', max_length=63, verbose_name='Name')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visibility', fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2, help_text='visibilityHelpText', verbose_name='Visibility')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='name', verbose_name='Slug')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='End')),
                ('all_day', models.BooleanField(default=False, verbose_name='All day')),
                ('email_reservations', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Reservation e-mail')),
                ('link_facebook', models.URLField(blank=True, null=True, verbose_name='Event on Facebook')),
                ('link_reservations', models.URLField(blank=True, null=True, verbose_name='Reservation link')),
                ('link_tickets', models.URLField(blank=True, null=True, verbose_name='Link to buy tickets')),
                ('description', fields.description.DescriptionField(blank=True, help_text='nameDescriptionText', null=True, verbose_name='Description')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Location', verbose_name='Location')),
                ('show_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='shows.ShowType', verbose_name='Show type')),
                ('sponsors', models.ManyToManyField(blank=True, to='profiles.Sponsor')),
            ],
            options={
                'verbose_name': 'Public Event',
                'verbose_name_plural': 'Public Events',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        )
    ]
