# Generated by Django 2.2.16 on 2020-09-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event'),
        ('shows', '0034_auto_20200920_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='show_type',
        ),
    ]
