# Generated by Django 2.2.16 on 2020-09-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_ticket_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='sponsors',
        ),
    ]
