# Generated by Django 2.2.16 on 2020-09-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20200903_2206'),
        ('events', '0011_auto_20200928_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='profiles.Sponsor'),
        ),
    ]
