# Generated by Django 2.2.16 on 2020-09-27 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200928_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventticketprice',
            old_name='show',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventParticipants', to='events.Event', verbose_name='Event'),
        ),
    ]
