# Generated by Django 2.2.16 on 2020-09-27 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200928_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticketprice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_prices', to='events.Event', verbose_name='Event'),
        ),
    ]
