# Generated by Django 2.2.16 on 2020-10-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200928_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canceled',
            field=models.BooleanField(default=False, help_text='Event has been canceled', verbose_name='Canceled'),
        ),
    ]
