# Generated by Django 2.2.dev20190104142447 on 2019-01-13 17:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import fields.name
import fields.visibility


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0002_auto_20190112_1615'),
        ('locations', '0002_auto_20190112_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', fields.name.NameField(help_text='nameHelpText', max_length=63, verbose_name='Name')),
                ('visibility', fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2, help_text='visibilityHelpText', verbose_name='Visibility')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='Slug')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('text', models.CharField(help_text='Enter words that will serve as an inspiration for this improvisation', max_length=255, verbose_name='Textual inspiration')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Location')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Show')),
            ],
            options={
                'verbose_name': 'Inspiration',
                'verbose_name_plural': 'Inspirations',
            },
        ),
    ]
