# Generated by Django 2.2.dev20190104142447 on 2019-01-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiration',
            name='discarded',
            field=models.BooleanField(default=False),
        ),
    ]
