---
- name: Setup all my servers on AWS
  hosts: web
  vars:
    django_archive: dist/polocas-napadu-api-{{ lookup("env", "PACKAGE_VERSION") }}.tar.gz
    django_config_file: local_settings.j2
    django_config: api.settings
    django_project_name: 'cz-polocas-napadu-api'
    django_project_environment: '{{ lookup("env", "DJANGO_PROJECT_ENVIRONMENT") }}'
    django_wsgi_file: api/wsgi.py

  roles:
    - role: practical-ansible.nginx-django

  post_tasks:
    - name: Configure Transaction cron job
      cron:
        name: 'Pair {{django_project_name}} transactions'
        minute: 0,30
        job: 'cd /var/www/{{django_project_name}}/{{django_project_environment}}/current && /var/www/{{django_project_name}}/{{django_project_environment}}/virtualenv/bin/python /var/www/{{django_project_name}}/{{django_project_environment}}/current/manage.py sync_accounts'
