---
name: 'Setup CI'
description: 'Setup CI to build django with advanced requirements'
runs:
  using: 'composite'
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry

    - name: Install system dependencies
      shell: bash
      run: sudo apt-get install python3-dev pkg-config gettext
