# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

workspace_root: &workspace_root
  ~/repo

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.7

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install pipenv vrun
            pipenv install --dev
            pipenv check

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Install gettext
          command: sudo apt-get install gettext

      - run:
          name: Compile messages
          command: ./.venv/bin/vrun pipenv run ./manage.py compilemessages

      - run:
          name: Lock requirements
          command: ./.venv/bin/vrun pipenv lock --requirements > requirements.txt

      - run:
          name: Compile artifacts
          command: ./.venv/bin/vrun python setup.py sdist

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Static code analysis
          command: ./.venv/bin/vrun pipenv run prospector

      - run:
          name: Tests
          command: ./.venv/bin/vrun pipenv run pytest --junitxml=/tmp/junit-test-report.xml --cov-config=.coveragerc --cov="."

      - run:
          name: Code Climate reporter
          command: ./.venv/bin/vrun pipenv run codeclimate-test-reporter

      - store_test_results:
          path: /tmp/junit-test-report.xml

  deploy-to-staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root
      - add_ssh_keys:
          fingerprints:
            - "47:1c:8b:3d:98:f9:c0:1c:7c:2d:77:e9:cd:46:da:cf"
      - run:
          name: Install ansible requirements
          command: ./.venv/bin/vrun pipenv run ansible-galaxy install -r requirements-ansible.yml
      - run:
          name: Configure ansible inventory
          command: echo -e "[web]\n${STAGING_DEPLOY_HOST}" > inventory.yml
      - run:
          name: Deploy to Staging
          command: >
            env
            PACKAGE_VERSION=$(python -c 'import version; print(version.PACKAGE_VERSION)')
            ALLOWED_HOSTS="$STAGING_ALLOWED_HOSTS"
            AWS_ACCESS_KEY_ID="$STAGING_AWS_ACCESS_KEY_ID"
            AWS_S3_REGION_NAME="$STAGING_AWS_S3_REGION_NAME"
            AWS_SECRET_ACCESS_KEY="$STAGING_AWS_SECRET_ACCESS_KEY"
            AWS_STORAGE_BUCKET_NAME="$STAGING_AWS_STORAGE_BUCKET_NAME"
            DB_HOST="$STAGING_DB_HOST"
            DB_NAME="$STAGING_DB_NAME"
            DB_PASSWORD="$STAGING_DB_PASSWORD"
            DB_USER="$STAGING_DB_USER"
            DJANGO_PROJECT_ENVIRONMENT="staging"
            DJANGO_SERVER_NAME="$STAGING_ALLOWED_HOSTS"
            EMAIL_MANAGER="$STAGING_EMAIL_MANAGER"
            SECRET_KEY="$STAGING_SECRET_KEY"
            RAVEN_DSN="$STAGING_RAVEN_DSN"
            DJANGO_ADMIN_SSO_OAUTH_CLIENT_ID="$STAGING_DJANGO_ADMIN_SSO_OAUTH_CLIENT_ID"
            DJANGO_ADMIN_SSO_OAUTH_CLIENT_SECRET="$STAGING_DJANGO_ADMIN_SSO_OAUTH_CLIENT_SECRET"
            ./.venv/bin/vrun pipenv run ansible-playbook deploy.yml -i inventory.yml

  deploy-to-production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root
      - add_ssh_keys:
          fingerprints:
            - "47:1c:8b:3d:98:f9:c0:1c:7c:2d:77:e9:cd:46:da:cf"
      - run:
          name: Install ansible requirements
          command: ./.venv/bin/vrun pipenv run ansible-galaxy install -r requirements-ansible.yml
      - run:
          name: Configure ansible inventory
          command: echo -e "[web]\n${PRODUCTION_DEPLOY_HOST}" > inventory.yml
      - run:
          name: Deploy to Production
          command: >
            env
            PACKAGE_VERSION=$(python -c 'import version; print(version.PACKAGE_VERSION)')
            ALLOWED_HOSTS="$PRODUCTION_ALLOWED_HOSTS"
            AWS_ACCESS_KEY_ID="$PRODUCTION_AWS_ACCESS_KEY_ID"
            AWS_S3_REGION_NAME="$PRODUCTION_AWS_S3_REGION_NAME"
            AWS_SECRET_ACCESS_KEY="$PRODUCTION_AWS_SECRET_ACCESS_KEY"
            AWS_STORAGE_BUCKET_NAME="$PRODUCTION_AWS_STORAGE_BUCKET_NAME"
            DB_HOST="$PRODUCTION_DB_HOST"
            DB_NAME="$PRODUCTION_DB_NAME"
            DB_PASSWORD="$PRODUCTION_DB_PASSWORD"
            DB_USER="$PRODUCTION_DB_USER"
            DJANGO_PROJECT_ENVIRONMENT="production"
            DJANGO_SERVER_NAME="$PRODUCTION_ALLOWED_HOSTS"
            EMAIL_MANAGER="$PRODUCTION_EMAIL_MANAGER"
            SECRET_KEY="$PRODUCTION_SECRET_KEY"
            RAVEN_DSN="$PRODUCTION_RAVEN_DSN"
            DJANGO_ADMIN_SSO_OAUTH_CLIENT_ID="$PRODUCTION_DJANGO_ADMIN_SSO_OAUTH_CLIENT_ID"
            DJANGO_ADMIN_SSO_OAUTH_CLIENT_SECRET="$PRODUCTION_DJANGO_ADMIN_SSO_OAUTH_CLIENT_SECRET"
            ./.venv/bin/vrun pipenv run ansible-playbook deploy.yml -i inventory.yml

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - deploy-to-staging:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - deploy-to-production:
          requires:
            - build
            - test
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
