# Generated by Django 2.2.16 on 2020-10-04 09:07

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import fields.visibility
import images.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0015_auto_20200928_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
                ('capacity', models.PositiveIntegerField(default=12, verbose_name='Capacity')),
            ],
            options={
                'verbose_name': 'Workshops',
                'verbose_name_plural': 'Workshops',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='WorkshopPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visibility', fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2, help_text='visibilityHelpText', verbose_name='Visibility')),
                ('image', images.fields.ImageField(height_field='height', help_text='imageHelpText', upload_to='var/photos', verbose_name='Image', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, default=100, editable=False, null=True)),
                ('width', models.PositiveIntegerField(blank=True, default=100, editable=False, null=True)),
                ('description', models.TextField(blank=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workshops.Workshop', verbose_name='Photos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
