# Generated by Django 2.2 on 2019-05-15 17:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import voting.models.live_poll_type_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivePollVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('vote_type', voting.models.live_poll_type_field.LivePollTypeField(choices=[(1, 'Audible vote')], default=1, help_text='pollTypeHelpText', verbose_name='Poll Type')),
            ],
            options={
                'verbose_name': 'Live Poll Voting',
                'verbose_name_plural': 'Live Poll Votings',
            },
        ),
        migrations.CreateModel(
            name='VolumeScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('volume', models.FloatField(verbose_name='Recorded volume')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_scrapes', to='voting.LivePollVoting', verbose_name='Live Poll Voting')),
            ],
            options={
                'verbose_name': 'Volume scrape',
                'verbose_name_plural': 'Volume scrapes',
            },
        ),
    ]
