# Generated by Django 2.2 on 2019-05-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0002_livepollvoting_closed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="volumescrape", old_name="vote", new_name="poll",
        ),
    ]
