# Generated by Django 2.2.10 on 2020-03-05 08:28

from django.db import migrations
import fields.weight


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_poem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='weight',
            field=fields.weight.WeightField(default=False, help_text='weightHelpText', verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='weight',
            field=fields.weight.WeightField(default=False, help_text='weightHelpText', verbose_name='Weight'),
        ),
    ]
