# Generated by Django 2.2.dev20190104142447 on 2019-01-20 10:57

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import fields.name


class Migration(migrations.Migration):

    dependencies = [
        ("theatre_sports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoulType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    fields.name.NameField(
                        help_text="nameHelpText", max_length=63, verbose_name="Name"
                    ),
                ),
                ("description", models.TextField(verbose_name="Textual inspiration")),
            ],
            options={"verbose_name": "FoulType", "verbose_name_plural": "Foul Types",},
        ),
        migrations.AlterField(
            model_name="foul",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fouls",
                to="games.Game",
            ),
        ),
        migrations.AddField(
            model_name="foul",
            name="foul_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fouls",
                to="theatre_sports.FoulType",
            ),
        ),
    ]
