# Generated by Django 3.0.dev20190119234541 on 2019-01-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre_sports", "0004_matchstage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestantgroup",
            name="contestant_type",
            field=models.PositiveIntegerField(
                choices=[(1, "team-home"), (2, "team-guest")]
            ),
        ),
    ]
