# Generated by Django 3.0.dev20190119234541 on 2019-01-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_auto_20190126_1557"),
        ("theatre_sports", "0005_auto_20190126_1402"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchstage",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stages",
                to="games.Game",
            ),
        ),
    ]
