# Generated by Django 3.0.dev20190126213846 on 2019-01-27 16:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre_sports", "0006_matchstage_game"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contestantgroup",
            options={
                "verbose_name": "Contestant Group",
                "verbose_name_plural": "Contestant Groups",
            },
        ),
        migrations.AddField(
            model_name="contestantgroup",
            name="color",
            field=colorfield.fields.ColorField(default="#ccc", max_length=18),
        ),
    ]
