# Generated by Django 2.1.5 on 2019-02-07 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20190113_1759'),
        ('theatre_sports', '0010_remove_scorepoint_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foul',
            name='match',
        ),
        migrations.AddField(
            model_name='foul',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fouls', to='shows.ShowParticipant'),
        ),
    ]
