# Generated by Django 2.2.7 on 2019-11-26 18:02

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_sports', '0021_auto_20190520_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='foultype',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='name', verbose_name='Slug'),
        ),
    ]
