# Generated by Django 2.2.16 on 2020-09-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_sports', '0024_auto_20200920_0331'),
        ('shows', '0040_delete_show_participant'),
        ('events', '0008_event_participant'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='ContestantGroup',
            name='players',
            field=models.ManyToManyField(
                related_name="contestant_groups",
                verbose_name="Players",
                to='events.EventParticipant',
            )
        ),
        migrations.AlterField(
            model_name='Foul',
            name='player',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="fouls",
                to='events.EventParticipant',
                verbose_name="Player",
            )
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
