# Generated by Django 2.2.16 on 2020-10-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_sports', '0026_auto_20201004_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestantgroupplayer',
            name='contestant_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre_sports.ContestantGroup'),
        ),
        migrations.AlterField(
            model_name='contestantgroupplayer',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventParticipant'),
        ),
    ]
