# Generated by Django 2.2.16 on 2020-10-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_sports', '0028_auto_20201004_1032'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='contestantgroup',
            name='players',
            field=models.ManyToManyField(related_name='contestant_groups', to='events.EventParticipant', verbose_name='Players'),
        ),
        migrations.DeleteModel(
            name='ContestantGroupPlayer',
        ),
    ]
    
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
