# Generated by Django 2.1.5 on 2019-01-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20190112_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='bands'),
        ),
    ]
