# Generated by Django 2.1.4 on 2018-12-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_bandphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='city',
            field=models.CharField(default=None, max_length=127),
            preserve_default=False,
        ),
    ]
