# Generated by Django 2.2 on 2019-04-15 00:30

from django.db import migrations
import fields.description


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_band_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandphoto',
            name='description',
            field=fields.description.DescriptionField(default=None, help_text='nameDescriptionText', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
