# Generated by Django 2.2.15 on 2020-08-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_auto_20190415_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandphoto',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
