# Generated by Django 2.2.11 on 2020-03-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('shows', '0023_auto_20200308_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTicket',
            fields=[
                ('orderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Orderable')),
                ('show_ticket_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.ShowTicketPrice', verbose_name='Show ticket price')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('orders.orderable',),
        ),
    ]
