# Generated by Django 2.2.11 on 2020-03-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showticket',
            name='used_on',
            field=models.DateTimeField(blank=True, help_text='Exact time the ticket was used', null=True, verbose_name='Used on'),
        ),
    ]
