# Generated by Django 2.1.4 on 2018-12-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '__first__'),
        ('bands', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('penalty_points', models.PositiveIntegerField(default=0)),
                ('results', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='score', to='shows.MatchResults')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_day', models.BooleanField()),
                ('description', models.TextField()),
                ('end', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('start', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'team-home'), (1, 'team-guest')])),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='bands.Band')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_band', to='shows.Show')),
            ],
        ),
        migrations.CreateModel(
            name='ShowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='show_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.ShowType'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='show_band',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='score', to='shows.ShowBand'),
        ),
        migrations.AddField(
            model_name='matchresults',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='match_results', to='shows.Show'),
        ),
    ]
