# Generated by Django 2.1.4 on 2018-12-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_showtypephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
