# Generated by Django 2.1.4 on 2018-12-22 13:07

from django.db import migrations
import fields.visibility


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20181221_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='visibility',
            field=fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AddField(
            model_name='showtype',
            name='visibility',
            field=fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='showphoto',
            name='visibility',
            field=fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='showtypephoto',
            name='visibility',
            field=fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
    ]
