# Generated by Django 2.2.1 on 2019-05-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0009_showvolumecalibrationvoting"),
    ]

    operations = [
        migrations.AddField(
            model_name="showvolumecalibration",
            name="closed",
            field=models.BooleanField(default=False, verbose_name="Closed"),
        ),
    ]
