# Generated by Django 2.2.1 on 2019-09-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0010_showvolumecalibration_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="link_facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="link_reservations",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="link_tickets",
            field=models.URLField(blank=True, null=True),
        ),
    ]
