# Generated by Django 2.2.1 on 2019-09-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0011_auto_20190919_0753"),
    ]

    operations = [
        migrations.AddField(
            model_name="showtype",
            name="short_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
