# Generated by Django 2.2.5 on 2019-09-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_auto_20190920_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='shows.ShowType', verbose_name='Show type'),
        ),
    ]
