# Generated by Django 2.2.6 on 2019-10-29 08:32

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0014_auto_20190923_0713"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                overwrite=True,
                populate_from="name",
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="showtype",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                overwrite=True,
                populate_from="name",
                verbose_name="Slug",
            ),
        ),
    ]
