# Generated by Django 2.2.7 on 2019-12-11 18:36

from django.db import migrations
import fields.description


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0017_showtype_use_games"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="description",
            field=fields.description.DescriptionField(
                blank=True,
                help_text="nameDescriptionText",
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
