# Generated by Django 2.2.10 on 2020-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0018_auto_20191211_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='email_reservations',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Reservation e-mail'),
        ),
        migrations.AlterField(
            model_name='show',
            name='link_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Event on Facebook'),
        ),
        migrations.AlterField(
            model_name='show',
            name='link_reservations',
            field=models.URLField(blank=True, null=True, verbose_name='Reservation link'),
        ),
        migrations.AlterField(
            model_name='show',
            name='link_tickets',
            field=models.URLField(blank=True, null=True, verbose_name='Link to buy tickets'),
        ),
    ]
