# Generated by Django 2.2.10 on 2020-03-04 16:39

from django.db import migrations
import fields.weight


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0019_auto_20200304_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='showrole',
            name='weight',
            field=fields.weight.WeightField(default=False, help_text='weightHelpText', verbose_name='Weight'),
        ),
    ]
