# Generated by Django 2.2.10 on 2020-03-05 09:32

import accounting.models.currency
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_pricelevel'),
        ('shows', '0020_showrole_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', accounting.models.currency.AmountField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount')),
                ('currency', accounting.models.currency.CurrencyField(choices=[('CZK', 'CZK'), ('EUR', 'EUR'), ('USD', 'USD')], default='CZK', help_text='ISO 4217 defined three letter currency abbreviation', max_length=3, verbose_name='Currency')),
                ('price_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_prices', to='accounting.PriceLevel', verbose_name='Price level')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_prices', to='shows.Show', verbose_name='Show')),
            ],
        ),
    ]
