# Generated by Django 2.2.10 on 2020-03-05 10:56

from django.db import migrations
import fields.weight


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0021_ticketprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showrole',
            name='weight',
            field=fields.weight.WeightField(default=100, help_text='weightHelpText', verbose_name='Weight'),
        ),
    ]
