# Generated by Django 2.2.11 on 2020-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0024_auto_20200309_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum amount of tickets to be sold', null=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='show',
            name='sell_tickets',
            field=models.BooleanField(default=False, help_text='Ticketing system will be enabled for this show', verbose_name='Sell tickets'),
        ),
    ]
