# Generated by Django 2.2.11 on 2020-03-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0025_auto_20200309_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showticketprice',
            options={'verbose_name': 'Show ticket price', 'verbose_name_plural': 'Show ticket prices'},
        ),
    ]
