# Generated by Django 2.2.16 on 2020-09-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0026_auto_20200903_2206'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='showrole',
            table='events_participantrole',
        ),
    ]
