# Generated by Django 2.2.16 on 2020-09-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0027_auto_20200919_2251'),
        ('events', '0003_create_participant_role'),
    ]

    state_operations = [
        migrations.DeleteModel('ShowRole'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
