# Generated by Django 2.2.16 on 2020-09-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0028_auto_20200919_2252'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='ShowParticipant',
            name='role',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="showsParticipants",
                to='events.ParticipantRole',
                verbose_name='Role',
            )
        )
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
