# Generated by Django 2.2.16 on 2020-09-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0029_auto_20200919_2310'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='show',
            table='events_event',
        ),
    ]
