# Generated by Django 2.2.16 on 2020-09-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0030_auto_20200920_0126'),
        ('events', '0004_update_content_types'),
    ]

    state_operations = [
        migrations.DeleteModel('Show'),
        migrations.AlterField(
            model_name='ShowParticipant',
            name='show',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="showsParticipants",
                to='events.Event',
                verbose_name='Show',
            )
        ),
        migrations.AlterField(
            model_name='ShowPhoto',
            name='profile',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="photos",
                to='events.Event',
            )
        ),
        migrations.AlterField(
            model_name='ShowTicketPrice',
            name='show',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="ticket_prices",
                to='events.Event',
                verbose_name='Show',
            )
        ),
        migrations.AlterField(
            model_name='ShowVolumeCalibration',
            name='show',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='volume_calibrations',
                to='events.Event',
                verbose_name='Show',
            )
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
