# Generated by Django 2.2.16 on 2020-09-20 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0032_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_type2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shows2', to='shows.ShowType', verbose_name='Show type'),
        ),
    ]
