# Generated by Django 2.2.16 on 2020-09-20 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0036_auto_20200920_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='shows.ShowType', verbose_name='Show type'),
            preserve_default=False,
        ),
    ]
