# Generated by Django 2.2.16 on 2020-09-20 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0037_auto_20200920_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showphoto',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shows.Show'),
        ),
        migrations.AlterField(
            model_name='showvolumecalibration',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_calibrations', to='shows.Show', verbose_name='Show'),
        ),
    ]
