# Generated by Django 2.2.16 on 2020-09-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0038_auto_20200920_0333'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='showparticipant',
            table='events_eventparticipant',
        ),
    ]
