# Generated by Django 2.2.16 on 2020-09-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0040_delete_show_participant'),
        ('events', '0008_event_participant'),
        ('games', '0010_retarget_event_participant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='showticketprice',
            table='events_eventticketprice',
        ),
    ]
