# Generated by Django 2.2.16 on 2020-09-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0042_delete_show_ticket_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showphoto',
            old_name='profile',
            new_name='show',
        ),
        migrations.AlterField(
            model_name='showphoto',
            name='show',
            field=models.ForeignKey(
                to="shows.Show",
                on_delete=models.CASCADE,
                related_name="photos",
                db_column='show_id'
            )
        ),
    ]
