# Generated by Django 2.2.16 on 2020-09-28 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0043_auto_20200928_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showphoto',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shows.Show'),
        ),
    ]
