# Generated by Django 2.2.26 on 2022-11-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0044_auto_20200928_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='use_inspirations',
            field=models.BooleanField(default=True, help_text='\n            Show will appear in the inspirations app and audience will be\n            allowed to put in suggestions for the improv scenes', verbose_name='Use inspirations'),
        ),
    ]
