# Generated by Django 4.1.3 on 2022-11-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0045_show_use_inspirations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="use_inspirations",
            field=models.BooleanField(
                default=True,
                help_text="\n            Show will appear in the inspirations app and audience will be\n            allowed to put in suggestions for the improv scenes\n        ",
                verbose_name="Use inspirations",
            ),
        ),
    ]
