# Generated by Django 2.2 on 2019-04-15 00:30

from django.db import migrations
import fields.description


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20190204_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerules',
            name='description',
            field=fields.description.DescriptionField(help_text='nameDescriptionText', verbose_name='Description'),
        ),
    ]
