# Generated by Django 2.2.7 on 2019-11-25 18:14

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190415_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerules',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='name', verbose_name='Slug'),
        ),
    ]
