# Generated by Django 2.2.11 on 2020-03-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='sender_appends_org',
            field=models.BooleanField(default=True, help_text='Organization name will be appended to the sender name,             resulting in things like "Karel from Poločasu nápadu"', verbose_name='Append organization to sender'),
        ),
    ]
