# Generated by Django 2.1.4 on 2018-12-22 13:07

from django.db import migrations
import fields.visibility


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_locationphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='visibility',
            field=fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='locationphoto',
            name='visibility',
            field=fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
    ]
