# Generated by Django 2.2 on 2019-04-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_auto_20190415_0030"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationphoto", name="description", field=models.TextField(),
        ),
    ]
