# Generated by Django 2.2.15 on 2020-08-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20190914_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationphoto',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
