# Generated by Django 2.2.6 on 2019-10-29 08:33

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0015_auto_20191029_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('customer_name', models.CharField(max_length=63)),
                ('customer_email', models.EmailField(max_length=254)),
                ('seat_count', models.PositiveIntegerField(default=1)),
                ('seat_location', models.PositiveIntegerField(choices=[(1, 'Whatever'), (2, 'First row'), (3, 'Middle'), (4, 'Far end')])),
                ('status', models.PositiveIntegerField(choices=[(1, 'Ordered'), (2, 'Confirmed'), (3, 'Canceled')])),
                ('newsletter', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Show')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
