# Generated by Django 2.2.16 on 2020-09-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_retarget_shows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='show',
            new_name='event',
        ),
    ]
