# Generated by Django 2.2.11 on 2020-03-09 15:21

import accounting.models.currency
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_extensions.db.fields
import fields.description
import fields.name
import fields.visibility
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0009_auto_20200308_2243'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(help_text='Physical world address', max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('postal_code', models.CharField(help_text='Postal/ZIP code', max_length=255, verbose_name='Postal code')),
                ('email', models.EmailField(help_text='E-mail address to send the invoice', max_length=254, verbose_name='E-mail address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', fields.description.DescriptionField(help_text='nameDescriptionText', verbose_name='Description')),
                ('name', fields.name.NameField(help_text='nameHelpText', max_length=63, verbose_name='Name')),
                ('visibility', fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2, help_text='visibilityHelpText', verbose_name='Visibility')),
                ('price', accounting.models.currency.AmountField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount')),
                ('currency', accounting.models.currency.CurrencyField(choices=[('CZK', 'CZK'), ('EUR', 'EUR'), ('USD', 'USD')], default='CZK', help_text='ISO 4217 defined three letter currency abbreviation', max_length=3, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Delivery method',
                'verbose_name_plural': 'Delivery methods',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ready'), (2, 'Canceled'), (3, 'Ordered'), (4, 'Paid'), (5, 'Delivered')], help_text='The current status of the order', verbose_name='Status')),
                ('buyer', models.ForeignKey(help_text='The entity buying thes product', on_delete=django.db.models.deletion.PROTECT, to='orders.Buyer', verbose_name='Buyer')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.DeliveryMethod', verbose_name='Delivery method')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('price', accounting.models.currency.AmountField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount')),
                ('currency', accounting.models.currency.CurrencyField(choices=[('CZK', 'CZK'), ('EUR', 'EUR'), ('USD', 'USD')], default='CZK', help_text='ISO 4217 defined three letter currency abbreviation', max_length=3, verbose_name='Currency')),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of this order', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', fields.description.DescriptionField(help_text='nameDescriptionText', verbose_name='Description')),
                ('name', fields.name.NameField(help_text='nameHelpText', max_length=63, verbose_name='Name')),
                ('visibility', fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2, help_text='visibilityHelpText', verbose_name='Visibility')),
                ('price', accounting.models.currency.AmountField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount')),
                ('currency', accounting.models.currency.CurrencyField(choices=[('CZK', 'CZK'), ('EUR', 'EUR'), ('USD', 'USD')], default='CZK', help_text='ISO 4217 defined three letter currency abbreviation', max_length=3, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Payment method',
                'verbose_name_plural': 'Payment methods',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('price', accounting.models.currency.AmountField(decimal_places=2, default=0, help_text='Item price at the time of order', max_digits=19, verbose_name='Price')),
                ('currency', accounting.models.currency.CurrencyField(choices=[('CZK', 'CZK'), ('EUR', 'EUR'), ('USD', 'USD')], default='CZK', help_text='ISO 4217 defined three letter currency abbreviation', max_length=3, verbose_name='Currency')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Orderable', verbose_name='Orderable')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.PaymentMethod', verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='order',
            name='promise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Promise', verbose_name='Promise'),
        ),
    ]
