# Generated by Django 2.2.11 on 2020-03-09 15:38

import accounting.models.currency
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderable',
            name='owner',
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this order', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='orderable',
            name='price',
            field=accounting.models.currency.AmountField(decimal_places=2, default=0, help_text='Catalogue price of this item', max_digits=19, verbose_name='Price'),
        ),
    ]
