# Generated by Django 2.2.11 on 2020-03-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200309_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ident',
            field=models.PositiveIntegerField(default=0, help_text='Unique identificator of the order', unique=True, verbose_name='Order number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ready'), (2, 'Canceled'), (3, 'Ordered'), (4, 'Paid'), (5, 'Delivered')], default=1, help_text='The current status of the order', verbose_name='Status'),
        ),
    ]
