# Generated by Django 2.2.10 on 2020-03-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiplevelfee',
            options={'verbose_name': 'Membership level fee', 'verbose_name_plural': 'Membership level fees'},
        ),
        migrations.AlterField(
            model_name='promise',
            name='constant_symbol',
            field=models.BigIntegerField(blank=True, help_text='Purpose code of the payment specified by Czech banking system.', null=True, verbose_name='constantSymbol'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='specific_symbol',
            field=models.BigIntegerField(blank=True, help_text='This number focuses variable symbol.', null=True, verbose_name='Specific symbol'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='variable_symbol',
            field=models.BigIntegerField(blank=True, help_text='Optional payment identifier', null=True, verbose_name='variableSymbol'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='constant_symbol',
            field=models.BigIntegerField(blank=True, help_text='Purpose code of the payment specified by Czech banking system.', null=True, verbose_name='constantSymbol'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='specific_symbol',
            field=models.BigIntegerField(blank=True, help_text='This number focuses variable symbol.', null=True, verbose_name='Specific symbol'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='variable_symbol',
            field=models.BigIntegerField(blank=True, help_text='Optional payment identifier', null=True, verbose_name='variableSymbol'),
        ),
    ]
