# Generated by Django 2.2.10 on 2020-03-02 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200301_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='known_account',
        ),
        migrations.AddField(
            model_name='statement',
            name='counter_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='accounting.CounterParty'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='repeat',
            field=models.CharField(blank=True, choices=[('P1M', 'Monthly'), ('P1Y', 'Yearly')], max_length=31, null=True, verbose_name='Repeat'),
        ),
    ]
