# Generated by Django 2.2.10 on 2020-03-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20200302_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterparty',
            options={'verbose_name': 'Counterparty', 'verbose_name_plural': 'Counterparties'},
        ),
        migrations.AlterModelOptions(
            name='purposecategory',
            options={'verbose_name': 'Purpose category', 'verbose_name_plural': 'Purpose categories'},
        ),
    ]
