# Generated by Django 2.2.10 on 2020-03-05 09:32

from django.db import migrations, models
import django_extensions.db.fields
import fields.description
import fields.name
import fields.visibility
import fields.weight


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20200304_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', fields.description.DescriptionField(help_text='nameDescriptionText', verbose_name='Description')),
                ('name', fields.name.NameField(help_text='nameHelpText', max_length=63, verbose_name='Name')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('visibility', fields.visibility.VisibilityField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2, help_text='visibilityHelpText', verbose_name='Visibility')),
                ('weight', fields.weight.WeightField(default=False, help_text='weightHelpText', verbose_name='Weight')),
                ('is_default', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
