# Generated by Django 2.2.10 on 2020-03-05 10:54

from django.db import migrations, models
import fields.weight


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_pricelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelevel',
            name='is_default',
            field=models.BooleanField(verbose_name='Default price level that will be used as fallback'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='weight',
            field=fields.weight.WeightField(default=100, help_text='weightHelpText', verbose_name='Weight'),
        ),
    ]
