# Generated by Django 2.2.11 on 2020-03-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20200307_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelevel',
            name='is_default',
            field=models.BooleanField(help_text='Default price level that will be used as fallback', verbose_name='Default'),
        ),
    ]
