# Generated by Django 2.2.15 on 2020-08-26 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20200308_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounting.MembershipLevel', verbose_name='Membership level'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='membershiplevelfee',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.MembershipLevel', verbose_name='Membership type'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promises', to='accounting.Purpose', verbose_name='Purpose'),
        ),
    ]
