# Generated by Django 2.2.11 on 2020-03-07 16:33

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('key', models.CharField(help_text='Key specific to the notification source', max_length=255, verbose_name='Notification key')),
                ('subject', models.CharField(help_text='Few words to describe contents of the e-mail', max_length=255, verbose_name='Subject')),
                ('sender_name', models.CharField(help_text='Name that will be displayed next to sender e-mail address', max_length=255, verbose_name='Sender name')),
                ('sender_email', models.EmailField(help_text='E-mail address of the sender', max_length=254, verbose_name='Sender email')),
                ('recipient_email', models.EmailField(help_text='E-mail address of the recipient', max_length=254, verbose_name='Recipient email')),
                ('scheduled_on', models.DateTimeField(help_text='System will proceed and send this e-mail after this datetime.', verbose_name='Scheduled on')),
                ('sent_on', models.DateTimeField(help_text='On this date and time, the e-mail was sent.', verbose_name='Sent on')),
                ('format', models.PositiveSmallIntegerField(choices=[(1, 'Text'), (2, 'HTML')], verbose_name='Format')),
                ('content', models.TextField(help_text='Enter formatted e-mail content. The text version will be auto             generated for HTML e-mails', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Inspiration',
                'verbose_name_plural': 'Inspirations',
            },
        ),
    ]
