# Generated by Django 2.2.11 on 2020-03-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotification',
            old_name='format',
            new_name='content_format',
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='sent_on',
            field=models.DateTimeField(blank=True, help_text='On this date and time, the e-mail was sent.', null=True, verbose_name='Sent on'),
        ),
    ]
