# Generated by Django 2.2.11 on 2020-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200307_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='ready',
            field=models.BooleanField(default=False, help_text='Ready e-mails will be sent at first valid oppoturnity after scheduled date', verbose_name='Ready to send'),
        ),
    ]
