# Generated by Django 2.2.11 on 2020-03-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emailnotification_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='sender_appends_org',
            field=models.BooleanField(default=True, help_text='Organization name will be appended to the sender name,             resulting in things like "Karel from Poločas nápadu"', verbose_name='Append organization to sender'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='sender_email',
            field=models.EmailField(default='karel@polocas-napadu.cz', help_text='E-mail address of the sender', max_length=254, verbose_name='Sender email'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='sender_name',
            field=models.CharField(default='Karel', help_text='Name that will be displayed next to sender e-mail address', max_length=255, verbose_name='Sender name'),
        ),
    ]
